import "./globals.css";
export const metadata = {
  title: 'Frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h2>Header here</h2>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <h2> Footer here</h2>
        </footer>
      </body>
    </html>
  )
}
